import Header from "@/components/Header.jsx";
import "./globals.css";
import {Metadata} from "next"
import Footer from "@/components/Footer.jsx";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { CartProvider } from "@/components/CartContext/CartContext";
import { WishlistProvider } from "@/components/WishlistContext/WishlistContext";
import { Toaster } from "react-hot-toast";



export const metadata = {
  title: "Shopcart Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <WishlistProvider>
      <CartProvider>
      <html lang="eng">
      <body className="font-Poppins antialiased">
       <div className="flex flex-col min-h-screen">
         <Header/>
         <main className="flex-1">
         {children}
         <Toaster position="bottom-right" reverseOrder={false} />
         </main>
        
        <Footer/>
       </div>
      </body>
      </html>
      
      </CartProvider>
      </WishlistProvider>
    </ClerkProvider>
  );
}

